### ISSUE TITLE
Calculate gene length

### ISSUE THREAD

**Issue by Matt-Schmitz** [NickJD/ORForise#14]
Hi Nick, it was great chatting with you today. I just want to mention one more tiny thing I noticed. In Comparator.py, you calculate gene length in the following way:
`gene_Length = (g_Stop - g_Start)`
Are g_Start and g_Stop the first and last bases of the gene? Wouldn't you have to add 1, because the length is start and stop inclusive (i.e. `gene_Length = (g_Stop - g_Start) + 1`)?

I look forward to giving you updates on my project as I continue my analysis.

**Comment by Matt-Schmitz** [comment]
Later in Comparator.py, `orf_Length` should have 1 added as well:
`orf_Length = (o_Stop - o_Start) +1`

By adding 1 to both gene_Length and orf_Length, the results of some metrics (Median_Length_of_All_ORFs, Minimum_Length_of_All_ORFs, Maximum_Length_of_All_ORFs) becomes a multiple of 3.

**Comment by NickJD** [comment]
Thanks again @Matt-Schmitz. I think I forgot to account for GFF 1-base system in some parts of the code.
![image](https://user-images.githubusercontent.com/5814452/227289672-4bfbeced-d04a-4f72-8830-295796df5149.png)
