### ISSUE TITLE
Inconsistent results for forward vs backward frames

### ISSUE THREAD

**Issue by deprekate** [NickJD/ORForise#15]
I tried gaming your script by creating six ORFs that span the entirety of all six frames (of Myco).  I expected it to get 100% partial, but it only got 41%
```
$ cat game.gff 
##gff-version 3
Chromosome	None	CDS	1	580074	.	+	.	
Chromosome	None	CDS	1	580074	.	-	.	
Chromosome	None	CDS	2	580075	.	+	.	
Chromosome	None	CDS	2	580075	.	-	.	
Chromosome	None	CDS	3	580076	.	+	.	
Chromosome	None	CDS	3	580076	.	-	.	
$ Annotation-Compare -dna Genomes/Myco.fa -ref Genomes/Myco.gff -t GFF -tp game.gff
Thank you for using ORForise
Please report any issues to: https://github.com/NickJD/ORForise/issues
#####
Genome Used: Myco.gff
Reference Used: Genomes/Myco.gff
Tool Compared: GFF
Perfect Matches: 0 [476] - 0.00%
Partial Matches: 199 [476] - 41.81%
Missed Genes: 277 [476] - 58.19%
```

I tracked down which CDS were missed, and they were all (277) forward CDS while all the (199) reverse CDS were 100% found
```
$ grep CDS Genomes/Myco.gff | cut -f7 | sort | uniq -c
    277 +
    199 -
```

**Comment by NickJD** [comment]
Thanks for this - I am going to try and look into it this week.

**Comment by NickJD** [comment]
I was looking for an elegant solution but decided to just get it fixed for now. It is on my long list to clean up the code but the newest release (v1.4.1 - 9b3417dfef4b509433852ed7316b218b8939d59c) should solve the problem.
