### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by tanmoy07m** [NickJD/ORForise#5]
![orforise](https://user-images.githubusercontent.com/64601421/214973289-89080f83-8b97-418a-9e84-087c298590c5.PNG)

Can .gff3 instead of .gff be used as input? I am new to python. Is this error specific to gff or due to numpy?

(orfwise) C:\Users\tmu258>Annotation-Compare -dna C:/Users/tmu258/orfwise/NZ_CP008776.fa -ref C:/Users/tmu258/orfwise/NZ_CP008776.gff -t Prodigal -tp C:/Users/tmu258/orfwise/prokka_GAS.gff
Thank you for using ORForise
Please report any issues to: https://github.com/NickJD/ORForise/issues
#####
Traceback (most recent call last):
  File "C:\Users\tmu258\Anaconda3\envs\orfwise\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tmu258\Anaconda3\envs\orfwise\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tmu258\Anaconda3\envs\orfwise\Scripts\Annotation-Compare.exe\__main__.py", line 7, in <module>
  File "C:\Users\tmu258\Anaconda3\envs\orfwise\lib\site-packages\ORForise\Annotation_Compare.py", line 184, in main
    comparator(options)
  File "C:\Users\tmu258\Anaconda3\envs\orfwise\lib\site-packages\ORForise\Annotation_Compare.py", line 70, in comparator
    all_Metrics, all_rep_Metrics, start_precision, stop_precision, other_starts, other_stops, perfect_Matches, missed_genes, unmatched_orfs, undetected_gene_metrics, unmatched_orf_metrics, orf_Coverage_Genome, matched_ORF_Coverage_Genome, gene_coverage_genome, multi_Matched_ORFs, partial_Hits = tool_comparison(
  File "C:\Users\tmu258\Anaconda3\envs\orfwise\lib\site-packages\ORForise\Comparator.py", line 392, in tool_comparison
    gene_Nuc_Array = np.zeros((comp.genome_Size), dtype=np.int)
  File "C:\Users\tmu258\Anaconda3\envs\orfwise\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'

**Comment by tanmoy07m** [comment]
Solved it through installing lower version of numpy
(orfxplorer) C:\Users\tmu258\StORF-Reporter\src>pip install "numpy<1.24.0"
Collecting numpy<1.24.0
  Downloading numpy-1.23.5-cp38-cp38-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 43.7 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.23.5


#########Test Run##########

(orfxplorer) C:\Users\tmu258\StORF-Reporter\src>Annotation-Compare -dna Myco.fa -ref Myco.gff -t Prodigal -tp Prodigal_Myco.gff
Thank you for using ORForise
Please report any issues to: https://github.com/NickJD/ORForise/issues
#####
Genome Used: Myco.gff
Reference Used: Myco.gff
Tool Compared: Prodigal
Perfect Matches: 128 [476] - 26.89%
Partial Matches: 62 [476] - 13.03%
Missed Genes: 286 [476] - 60.08%

**Comment by NickJD** [comment]
Thanks for noting this issue.

**Comment by NickJD** [comment]
Thanks for noting this issue. I think in numpy >=1.24.0 there was a change to the alias for 'np.int' etc which causes some current code to break. I will put a numpy version limit into the pip build package in the next release to hopefully fix this until a better workaround can be found. Thanks again!
