### ISSUE TITLE
GFF adder/Intersector

### ISSUE THREAD

**Issue by tanmoy07m** [NickJD/ORForise#6]
Thank you for the nice code. I am new to python and TnSeq analysis. Currently i use different gene annotation tool and try to merge them for use in TnSeq analysis. For the analysis, I require the locus tag for each orf. I wrote a code which does the job but I found the ORFwise useful with more desired features.  I was wondering if there is any way you will be adding the feature of writing the “ID” attribute or 9th column from the both the reference and tool generated gff files to the output files of gff adder/intersector? The resulting output gff file will be helpful for me to be used in further TnSeq analysis. 
Thank you in advance

**Comment by NickJD** [comment]
Hi, I would be happy to add any features you think may be useful. Could you please send me an example of a GFF line showing exactly what you mean so I can better understand what you need.

**Comment by tanmoy07m** [comment]
Thank you for the help!
Here is an example of gff file (Requested GFF-Adder Output section) that I generally use for downstream analysis. Eventually I convert them to Prot_Table Format using a package for further analysis. 

******Current GFF-Adder Output********
##sequence-region NZ_CP008776.1 1 14
##gff-version	3
#	GFF-Adder
#	Run Date:2023-02-01
##Genome DNA File:NZ_CP008776.fa
##Original File: NZ_CP008776.gff
##Additional File: prokka_GAS.gff
NZ_CP008776.1	Reference_Annotation	CDS	45899	47191	.	+	.	ID=Original_Annotation_ref;Length=1292
NZ_CP008776.1	Reference_Annotation	CDS	47323	48234	.	+	.	ID=Original_Annotation_ref;Length=911
NZ_CP008776.1	Prodigal	CDS	48318	48413	.	+	.	ID=Additional_Annotation_StORF_0;Length=95

#missing ncRNA
NZ_CP008776.1	Reference_Annotation	CDS	183536	184768	.	-	.	ID=Original_Annotation_ref;Length=1232
NZ_CP008776.1	Reference_Annotation	CDS	185168	185872	.	+	.	ID=Original_Annotation_ref;Length=704

******Requested GFF-Adder Output********

NZ_CP008776.1	RefSeq	gene	45899	47191	.	+	.	ID=gene-SP5448_RS00255;Name=purB;gbkey=Gene;gene=purB;gene_biotype=protein_coding;locus_tag=SP5448_RS00255;old_locus_tag=SP5448_00265
NZ_CP008776.1	Protein Homology	CDS	45899	47191	.	+	0	ID=cds-WP_010921780.1;Parent=gene-SP5448_RS00255;Dbxref=Genbank:WP_010921780.1;Name=WP_010921780.1;Ontology_term=GO:0009152,GO:0004018;gbkey=CDS;gene=purB;go_function=N6-(1%2C2-dicarboxyethyl)AMP AMP-lyase (fumarate-forming) activity|0004018||IEA;go_process=purine ribonucleotide biosynthetic process|0009152||IEA;inference=COORDINATES: similar to AA sequence:RefSeq:WP_014407197.1;locus_tag=SP5448_RS00255;product=adenylosuccinate lyase;protein_id=WP_010921780.1;transl_table=11
NZ_CP008776.1	RefSeq	gene	47323	48234	.	+	.	ID=gene-SP5448_RS00260;Name=rgg4;gbkey=Gene;gene=rgg4;gene_biotype=protein_coding;locus_tag=SP5448_RS00260;old_locus_tag=SP5448_00270
NZ_CP008776.1	Protein Homology	CDS	47323	48234	.	+	0	ID=cds-WP_002986681.1;Parent=gene-SP5448_RS00260;Dbxref=Genbank:WP_002986681.1;Name=WP_002986681.1;gbkey=CDS;gene=rgg4;inference=COORDINATES: similar to AA sequence:RefSeq:WP_002986681.1;locus_tag=SP5448_RS00260;product=transcriptional regulator Rgg4/ComR;protein_id=WP_002986681.1;transl_table=11
NZ_CP008776.1	prokka	gene	48318	48413	.	+	.	ID=sp5448_00055_gene;locus_tag=sp5448_00055
NZ_CP008776.1	Prodigal:002006	CDS	48318	48413	.	+	0	ID=sp5448_00055;Parent=sp5448_00055_gene;inference=ab initio prediction:Prodigal:002006;locus_tag=sp5448_00055;product=hypothetical protein;protein_id=gnl|mseq|sp5448_00055

### ncRNA in original GFF, Currently it seems like GFF-adder discards anything that is not CDS,rRNA,tRNA***********

NZ_CP008776.1	RefSeq	gene	184968	185066	.	+	.	ID=gene-SP5448_RS09185;Name=ffs;gbkey=Gene;gene=ffs;gene_biotype=SRP_RNA;locus_tag=SP5448_RS09185
NZ_CP008776.1	cmsearch	SRP_RNA	184968	185066	.	+	.	ID=rna-SP5448_RS09185;Parent=gene-SP5448_RS09185;Dbxref=RFAM:RF00169;gbkey=ncRNA;gene=ffs;inference=COORDINATES: profile:INFERNAL:1.1.1;locus_tag=SP5448_RS09185;product=signal recognition particle sRNA small type


********Eventually I convert them to Prot_Table Format for further analysis*************

adenylosuccinate lyase	45899	47191	+	431	-	-	purB	SP5448_RS00255	- #### the gene name, locus_tag and short description helps in quic
transcriptional regulator Rgg4/ComR	47323	48234	+	304	-	-	rgg4	SP5448_RS00260	-
quorum-sensing system DWW-type pheromone	48318	48413	+	32	-	-	-	sp5448_00055	- #### New locus_tag assigned to predicted annotation

**Comment by NickJD** [comment]
Hi, I think I understand but am still a little unclear on a few things. Can you please attach the FASTA and the two GFF files here or email me them at 'nicholas@dimonaco.co.uk' so I can better understand the data. I still think I need to make some changes but you can use the '-gi' option to include other gene features from the original annotation.
