### ISSUE TITLE
Median_Stop_Difference_of_Matched_ORFs is NA

### ISSUE THREAD

**Issue by thh32** [NickJD/ORForise#7]
Hey Nick,

When running ORForise on Prodigal, or GeneMarkS, we get N/A as "Median_Stop_Difference_of_Matched_ORFs";

```
Percentage_of_Genes_Detected,Percentage_of_ORFs_that_Detected_a_Gene,Percent_Difference_of_All_ORFs,Median_Length_Difference,Percentage_of_Perfect_Matches,Median_Start_Difference_of_Matched_ORFs,Median_Stop_Difference_of_Matched_ORFs,Percentage_Difference_of_Matched_Overlapping_CDSs,Percent_Difference_of_Short-Matched-ORFs,Precision,Recall,False_Discovery_Rate
98.05,93.22,5.13,-2.48,94.21,-3.0,N/A,-3.61,-16.87,0.93,0.98,0.07
```

Any idea what is causing this and how it might be fixed?

Thanks,
Tom

**Comment by thh32** [comment]
We have just gone through the output further and realised it is due to there being no stop differences, hence no values to calculate a median from!

**Comment by NickJD** [comment]
Exactly! I can't calculate it so it defaults to N/A. I hope to write a better manual at some point.
