### ISSUE TITLE
GFF input

### ISSUE THREAD

**Issue by Matt-Schmitz** [NickJD/ORForise#8]
I tried downloading the not yet released ORForise 1.3.0 and I got an error for my GFF pyrodigal input.
```
  File "/home/matt/ORForise_1.3.0/ORForise/src/ORForise/Tools/GFF/GFF.py", line 14, in GFF
    types = args[2]
IndexError: tuple index out of range
```
 
 
args[2] doesn’t exist, but the types variable is compared to line[2] later on.
```
gene_types = types.split(',')
if any(gene_type == line[2] for gene_type in gene_types)and len(line) == 9:
```
 
 
I checked what line[2] was equal to. It’s value is “CDS”, so I just set types equal to “CDS” as well to see what would happen (`types = "CDS"`). The code ran and I got an output. It’s a pretty hacky solution though and you have a commented out part later on where it looks like you're working on “CDS”.
```
                # elif "CDS" in line[2]:
                #     sys.exit("SAS")
```

Here is the file:
[pyrodigal_E-coli.gff](https://github.com/NickJD/ORForise/files/10812565/pyrodigal_E-coli.txt)

**Comment by NickJD** [comment]
Hey. Thanks for bringing this up. I have a lot of half finished work arounds I intend on fixing in the coming month. Can you please send me the runtime command you gave to ORForise? I think I also need to make a specific call for Pyrodigal as it is starting to become a widely-used tool in it's own right. I will append your fix and push over the next few days.

**Comment by Matt-Schmitz** [comment]
Sure, here's the command I ran:
`python3 Annotation_Compare.py -dna ~/ORForise/ORForise-1.2.2/Genomes/E-coli.fa -ref ~/ORForise/ORForise-1.2.2/Genomes/E-coli.gff -tp ~/ORForise/ORForise-1.2.2/Genomes/ORForise_input/pyrodigal_E-coli.gff -t GFF -o pyrodigal.out`

It's the 1.3.0 version of ORForise, but I accessed the genome and annotations in the old 1.2.2 folder.

**Comment by NickJD** [comment]
This was fixed in a previous version and should have been closed last year. Sorry for not picking it up.
