### ISSUE TITLE
Negative r_Start values

### ISSUE THREAD

**Issue by Matt-Schmitz** [NickJD/ORForise#9]
Hi Nick, I've tried to use ORForise with a gff file produced by Balrog, but I'm getting the following error:

```
  File "/home/matt/ORForise_1.3.0/ORForise/src/ORForise/Comparator.py", line 79, in nuc_Count
    gc_content = (g + c) * 100 / (a + t + g + c + n)
ZeroDivisionError: division by zero
```

I've found the cause as well. Balrog predicts genes that go past the end and start back at the beginning (2764701 > 2764699).

##gff-version 3
##sequence-region Chromosome 1 **2764699**
Chromosome	balrog	CDS	114	308	.	-	0	inference=ab initio prediction:Balrog;product=hypothetical protein

Chromosome	balrog	CDS	2760738	2762504	.	-	0	inference=ab initio prediction:Balrog;product=hypothetical protein
Chromosome	balrog	CDS	2762556	2763095	.	-	0	inference=ab initio prediction:Balrog;product=hypothetical protein
Chromosome	balrog	CDS	2763494	**2764701**	.	-	0	inference=ab initio prediction:Balrog;product=hypothetical protein

This leads to a negative value of r_Start.

```
def nuc_Count(start, stop, strand):  # Gets correct seq then returns GC
    if strand == '-':
        r_Start = comp.genome_Size - stop
        r_Stop = comp.genome_Size - start
        seq = (comp.genome_Seq_Rev[r_Start:r_Stop + 1])
```

[balrogcpp-Staph.gff](https://github.com/NickJD/ORForise/files/10854289/balrogcpp-nick-Staph.txt)

**Comment by NickJD** [comment]
I will close this issue for now as I have accounted for the crash in the code by adding the 'extra' bases from the start/end of the genome according to the wrap around loci. 
@https://github.com/NickJD/ORForise/releases/tag/v1.4.2
